```{r Namers}
# Set up some path name parameters
filenamer<-paste("General Customer Import",Sys.Date())
pathnamer<-paste("I:\\live\\Orders to import\\Import Files",filenamer,".xlsx")
```

```{r Autofilereader, include = FALSE}
# Read all files in the staging folder
farm<-list.files("\\\\CPSL2K12\\PropellaEDI\\live\\Orders to import",pattern = "Book",full.names=TRUE)%>%lapply(.,read_xlsx)%>% reduce(full_join)
aciem<-list.files("\\\\CPSL2K12\\PropellaEDI\\live\\Orders to import",pattern = "Order_",full.names=TRUE)%>%lapply(.,read_xlsx, skip = 5)%>% reduce(full_join)
smart<-list.files("\\\\CPSL2K12\\PropellaEDI\\live\\Orders to import",pattern = "-export",full.names=TRUE)%>%lapply(.,read.csv)%>% reduce(full_join)
biw<-list.files("\\\\CPSL2K12\\PropellaEDI\\live\\Orders to import",pattern = "BIPO",full.names=TRUE)%>%lapply(.,xl.read.file,password = "CPS2021")%>%do.call(rbind,.)
```

```{r FARMSOURCE, include = FALSE}
# Add new blank columns
farm['Cust No']="" #20
farm['Stkpt']="" #21
farm['Ref']="" #22
farm['Addr4']="" #23

# Rearrange the table
importfarm<-farm[c(3,22,1,20,10,11,12,23,14,13,15,16,8,21,5,9)]

# Change the column headings to match XLSX import format
colnames(importfarm)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

# Hard code the country value, add last names to last name column, update first name column
importfarm['Cust No']<-c(replicate(nrow(farm),"FAR001"))
importfarm['Stkpt']<-c(replicate(nrow(farm),"CPS"))
importfarm['OrdDate']<-c(format(importfarm$OrdDate, format = "%d/%m/%Y"))
importfarm['Pcode']<-c(as.character(importfarm$Pcode))
importfarm['City']<-c(gsub("\\d{4}","",importfarm$City))
```

```{r ACIEM, include = FALSE}
# Add new blank columns
aciem['Cust No']="" #15
aciem['Stkpt']="" #16
aciem['Pcode']="" #17
aciem['Email']="" #18
aciem['Order Date']="" #19
aciem['Ref']="" #20

# Rearrange the table
importaciem<-aciem[c(1,20,19,15,8,9,10,11,12,17,13,18,6,16,2,4)]

# Change the column headings to match XLSX import format
colnames(importaciem)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

# Hard code the country value, add last names to last name column, update first name column, find postcodes
pcodesearch1<-c(str_extract(importaciem$Addr2,"\\d{4}"))
pcodesearch2<-c(str_extract(importaciem$Addr3,"\\d{4}"))
pcodesearch3<-c(str_extract(importaciem$Addr4,"\\d{4}"))
pcodesearch4<-c(str_extract(importaciem$City,"\\d{4}"))
pcodefinal<-coalesce(pcodesearch1,pcodesearch2,pcodesearch3,pcodesearch4)
importaciem['OrdDate']<-format(today(), format = "%d/%m/%Y")
importaciem['Cust No']<-c(replicate(nrow(aciem),"AIM001"))
importaciem['Stkpt']<-c(replicate(nrow(aciem),"CPS"))
importaciem['Pcode']<-pcodefinal
importaciem['City']<-c(gsub("\\d{4}","",importaciem$City))
#apply(importaciem[6:8],2, function (x) gsub("\\d{4}","",x))
```

```{r SMARTTRADE, include = FALSE}
# Add new blank columns and take names out of mobile field
smart['Cust No']="" #17
smart['Stkpt']="" #18
smart['Ref']="" #19
smart['Addr4']="" #20
smart['Email']="" #21

# Rearrange the table 
importsmart<-smart[c(2,19,1,17,6,10,11,20,12,13,9,21,15,18,3,16)]

# Change the column headings to match XLSX import format
colnames(importsmart)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

# Hard code the country value, clean any names out of phone number field
importsmart['Cust No']<-c(replicate(nrow(smart),"SMA001"))
importsmart['Stkpt']<-c(replicate(nrow(smart),"CPS"))
bnamelist<-c(smart$businessName)
indlist<-c(smart$individualName)
fulldelname<-paste(smart$individualName,"c/-",smart$businessName)
importsmart['Addr1']=fulldelname
importsmart['Phone']<-c(gsub("[a-zA-Z ]", "", importsmart$Phone))
importsmart['CustOrd']<-c(as.character(importsmart$CustOrd))
importsmart['Pcode']<-c(as.character(importsmart$Pcode))
importsmart['City']<-c(gsub("\\d{4}","",importsmart$City))
```

```{r BIW, include = FALSE}
# Add new blank columns
biw['Cust No']="" #41
biw['Stkpt']="" #42
biw['Ref']="" #43

# Rearrange the table
importbiw<-biw[c(1,43,2,41,26,27,28,29,31,33,35,36,10,42,5,8)]

# Change the column headings to match XLSX import format
colnames(importbiw)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

# Hard code the country value, tidy phone numbers
importbiw['Cust No']<-c(replicate(nrow(biw),"BIW001"))
importbiw['Stkpt']<-c(replicate(nrow(biw),"CPS"))
importbiw['Phone']<-c(gsub("[^0-9]","",importbiw$Phone))
importbiw['OrdDate']<-c(format(ymd(importbiw$OrdDate), format = "%d/%m/%Y"))
importbiw['Pcode']<-c(as.character(importbiw$Pcode))
importbiw['City']<-c(gsub("\\d{4}","",importbiw$City))
```

```{r combineprint}
printlist<-list(importaciem,importbiw, importfarm, importsmart)
printlist%>%reduce(full_join)%>%write_xlsx(.,paste("C:\\Users\\Darren\\Desktop\\General customer import",today(),".xlsx"))
```

```{r Archive raw files}
# Move the raw order files to an archive folder
newarchive<-dir.create(paste0("I:\\live\\Orders to import\\Archive ",now()))
archivelist<-list.files("I:\\live\\Orders to import", pattern = "\\.", full.names = TRUE)%>%file.move(.,newarchive, overwrite = FALSE)
```
across(importaciem[5:8],gsub("\\d{4}","")
