---
This code will read all files in the EDI/Live/Orders to import folder and do the following

1. Combine all files into one table per customer
2. Add all missing fields required to meet the Propella .xlsx import format
3. Hardcode all required values for correct import functionality
4. Manipulate and clean data
5. Combine all tables into a single table formatted for Propella .xlsx import
6. Create the file in EDI/Live/Orders to import/Import Files
7. Create an archive with today's date in EDI/Live/Orders to import/Archive
8. Move all files from EDI/Live/Orders to import -> EDI/Live/Orders to import/Archive/YYYY-MM-DD

---

```{r warnings, include = FALSE, echo = FALSE}
defaultW <- getOption("warn") 
options(warn = -1) 
```

```{r Namers, echo = FALSE}
# Set up some path name parameters
filenamer<-paste("temp file",Sys.Date())
pathnamer<-paste("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import\\Import Files\\",filenamer,".csv")
tablebuilder<-function(x){write.table(x, pathnamer, sep = ",", row.names = FALSE, col.names =! file.exists(pathnamer), append = TRUE)}
```

```{r Autofilereader, include = FALSE, echo = FALSE}
# Read all files in the staging folder
farm<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^FS CPSL Orders",full.names=TRUE)%>%lapply(.,read_xlsx)%>%do.call(rbind,.)
aciem<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^Order_",full.names=TRUE)%>%lapply(.,read_xlsx, skip = 5)%>%do.call(rbind,.)
smart<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^SL CPSL Orders",full.names=TRUE)%>%lapply(.,read_xlsx)%>%do.call(rbind,.)
biw<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^BIPO",full.names=TRUE)%>%lapply(.,xl.read.file,password = "CPS2021")%>%do.call(rbind,.)%>%as_tibble()
pgg<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^CPS \\d{2}",full.names=TRUE)%>%lapply(.,read_xlsx)%>%do.call(rbind,.)
isl1<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^CPSL-Orders-from-ISL",full.names=TRUE)%>%lapply(.,read.csv)%>%do.call(rbind,.)%>%as_tibble()
isl2<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^ISLPO\\d{6}",full.names=TRUE)%>%lapply(.,read.csv)%>%do.call(rbind,.)%>%as_tibble()
colnames(isl2) = c(names(isl1))
isl<-rbind(isl1,isl2)
iml<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^IML GROUP",full.names=TRUE)%>%lapply(.,read_xlsx)%>%do.call(rbind,.)
sime<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^\\d{7}", full.names = TRUE)%>%lapply(.,read_csv, show_col_types = FALSE)%>%do.call(rbind,.)%>%as_tibble()
#viridian<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "^\\w{7,10} CPS Orders",full.names=TRUE)%>%lapply(.,read_xlsx)%>%do.call(rbind,.)
mico<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import",pattern = "OrderData",full.names=TRUE)%>%lapply(.,read.delim, sep = "|", header = TRUE)%>%do.call(rbind,.)%>%as_tibble()
```

```{r FARMSOURCE, include = FALSE, eval = exists(farm)}
tryCatch({
# Add new blank columns
farm['Cust No']="" #20
farm['Stkpt']="" #21
farm['Ref']="" #22
farm['Addr4']="" #23
farm['Email']="" #24

# Rearrange the table
impfarm<-farm[c(3,22,1,20,10,11,12,23,14,13,15,24,8,21,5,9)]

# Change the column headings to match XLSX import format
colnames(impfarm)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
impfarm['Cust No']<-c(replicate(nrow(farm),"FAR001"))
impfarm['Stkpt']<-c(replicate(nrow(farm),"CPS"))
impfarm['OrdDate']<-c(format(farm$order_date, format = "%d/%m/%Y"))
impfarm['Pcode']<-c(as.character(impfarm$Pcode))
impfarm['Phone']<-c(as.character(impfarm$Phone))

tablebuilder(impfarm)
},
error = function(e){message("No FARM orders to process")})
```

```{r ACIEM, include = FALSE, eval = exists(aciem)}
tryCatch({
# Add new blank columns
aciem['Cust No']="" #15
aciem['Stkpt']="" #16
aciem['Pcode']="" #17
aciem['Email']="" #18
aciem['Order Date']="" #19
aciem['Ref']="" #20

# Rearrange the table
impaciem<-aciem[c(1,20,19,15,8,9,10,11,12,17,13,18,6,16,2,4)]

# Change the column headings to match XLSX import format
colnames(impaciem)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
pcodesearch1<-c(str_extract(impaciem$Addr2,"\\d{4}"))
pcodesearch2<-c(str_extract(impaciem$Addr3,"\\d{4}"))
pcodesearch3<-c(str_extract(impaciem$Addr4,"\\d{4}"))
pcodesearch4<-c(str_extract(impaciem$City,"\\d{4}"))
pcodefinal<-coalesce(pcodesearch1,pcodesearch2,pcodesearch3,pcodesearch4)
impaciem['OrdDate']<-format(today(), format = "%d/%m/%Y")
impaciem['Cust No']<-c(replicate(nrow(aciem),"AIM001"))
impaciem['Stkpt']<-c(replicate(nrow(aciem),"CPS"))
impaciem['Pcode']<-pcodefinal

tablebuilder(impaciem)
},
error = function(e){message("No ACIEM orders to process")})
```

```{r SMARTTRADE, include = FALSE, eval = exists(smart)}
tryCatch({
# Add new blank columns and take names out of mobile field
smart['Ref']="" #20
smart['Cust No']="" #21
smart['Addr4']="" #22
smart['Email']="" #23
smart['Stkpt']="" #24

# Rearrange the table 
impsmart<-smart[c(3,20,1,21,10,11,12,22,14,13,15,23,8,24,5,9)]

# Change the column headings to match XLSX import format
colnames(impsmart)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
impsmart['Cust No']<-c(replicate(nrow(smart),"SMA001"))
impsmart['Stkpt']<-c(replicate(nrow(smart),"CPS"))
#bnamelist<-c(smart$businessName)
#indlist<-c(smart$individualName)
#fulldelname<-paste(smart$individualName,"c/-",smart$businessName)
#impsmart['Addr1']<-c(fulldelname)
impsmart[is.na(impsmart)]<-""
impsmart['Phone']<-c(gsub("[a-zA-Z ]", "", impsmart$Phone))
impsmart['CustOrd']<-c(as.character(impsmart$CustOrd))
impsmart['Pcode']<-c(as.character(impsmart$Pcode))

tablebuilder(impsmart)
},
error = function(e){message("No SMART TRADE orders to process")})
```

```{r BIW, include = FALSE, eval = exists(biw)}
tryCatch({
# Add new blank columns
biw['Cust No']="" #41
biw['Stkpt']="" #42
biw['Ref']="" #43

# Rearrange the table
impbiw<-biw[c(1,43,2,41,26,27,28,29,31,33,35,36,10,42,5,8)]

# Change the column headings to match XLSX import format
colnames(impbiw)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
impbiw['Cust No']<-c(replicate(nrow(biw),"BIW001"))
impbiw['Stkpt']<-c(replicate(nrow(biw),"CPS"))
impbiw['Phone']<-c(gsub("[^0-9]","",impbiw$Phone))
impbiw['OrdDate']<-c(format(ymd(impbiw$OrdDate), format = "%d/%m/%Y"))
impbiw['Pcode']<-c(as.character(impbiw$Pcode))

tablebuilder(impbiw)
},
error = function(e){message("No BIW orders to process")})
```

```{r PGG, include = FALSE, eval = exists(pgg)}
tryCatch({
# Add new blank columns
pgg['Addr4']="" #14
pgg['Email']="" #15
pgg['Stkpt']="" #16
pgg['Freight']="" #17

# Rearrange the table
imppgg<-pgg[c(2,4,1,3,8,9,10,14,11,12,13,15,15,17,5,7)]

# Change the column headings to match XLSX import format
colnames(imppgg)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
imppgg['Cust No']<-c(replicate(nrow(pgg),"PGG001"))
imppgg['Stkpt']<-c(replicate(nrow(pgg),"CPS"))
imppgg[1:2]<-apply(imppgg[1:2],2, function (x) as.character(x))
imppgg['OrdDate']<-c(format(imppgg$OrdDate, format = "%d/%m/%Y"))
imppgg['Pcode']<-apply(imppgg[10],2, function (x) as.character(x))
imppgg['Freight Value']<-as.numeric(0)

tablebuilder(imppgg)
},
error = function(e){message("No PGG orders to process")})
```

```{r ISL, include = FALSE, eval = exists(isl)}
tryCatch({
# Add new blank columns
isl['Ref']="" #18
isl['Cust No']="" #19
isl['Email']="" #20
isl['Stkpt']="" #21

# Rearrange the tab
impisl<-isl[c(1,18,2,19,9,10,11,12,13,15,16,20,7,21,4,3)]

# Change the column headings to match XLSX import format
colnames(impisl)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
impisl['Cust No']<-c(replicate(nrow(isl),"INV001"))
impisl['Stkpt']<-c(replicate(nrow(isl),"CPS"))
impisl[10:11]<-lapply(impisl[10:11], function (x) as.character(x))
impisl['Phone']<-c(as.character(impisl$Phone))
impisl['Freight Value']<-as.numeric(0)

tablebuilder(impisl)
},
error = function(e){message("No ISL orders to process")})
```

```{r IML, include = FALSE, eval = exists(iml)}
tryCatch({
# Add new blank columns
iml['Ref']<-"" #17
iml['Addr4']="" #18
iml['Email']="" #19
iml['Stkpt']="" #20

# Rearrange the table
impiml<-iml[c(3,17,1,2,10,11,12,18,13,14,15,19,8,20,4,6)]

# Change the column headings to match XLSX import format
colnames(impiml)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
impiml['CustOrd']<-c(as.character(impiml$CustOrd))
impiml['OrdDate']<-c(format(impiml$OrdDate, format = "%d/%m/%Y"))
impiml['Cust No']<-c(gsub("IML","IML001",impiml$`Cust No`))
impiml['Stkpt']<-c(replicate(nrow(iml),"CPS"))
impiml['Pcode']<-c(as.character(impiml$Pcode))

tablebuilder(impiml)
},
error = function(e){message("No IML orders to process")})
```

```{r SIME DERBY, include = FALSE, eval = exists(sime)}
tryCatch({
# Rearrange the table
impsime<-as_tibble(sime)

# Change the column headings to match XLSX import format
colnames(impsime)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
impsime['CustOrd']<-c(as.character(impsime$CustOrd))
impsime['Pcode']<-apply(impsime[10],2, function (x) as.character(x))
impsime['Freight Value']<-as.numeric(0)

tablebuilder(impsime)
},
error = function(e){message("No SIME DERBY orders to process")})
```

```{r VIRIDIAN, include = FALSE, eval = exists(viridian)}
tryCatch({
# Add new blank columns
viridian['Ref']<-"" #16
viridian['Ord Date']="" #17
viridian['Cust No']="" #18
viridian['Addr1']="" #19
viridian['Addr4']="" #20
viridian['Freight Value']="" #21
viridian['Stkpt']="" #22

# Rearrange the table
impviridian<-viridian[c(2,16,17,18,19,6,9,20,10,11,12,14,21,22,3,8)]

# Change the column headings to match XLSX import format
colnames(impviridian)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
impviridian['OrdDate']<-c(format(today(), format = "%d/%m/%Y"))
impviridian['Cust No']<-c(replicate(nrow(viridian),"VGL001"))
impviridian['Addr1']<-c(paste(viridian$`First Name`," ",viridian$`Last Name`))
impviridian['Stkpt']<-c(replicate(nrow(viridian),"CPS"))
impviridian['Pcode']<-apply(impviridian[10],2, function (x) as.character(x))
impviridian['Freight Value']<-as.numeric(0)

tablebuilder(impviridian)
},
error = function(e){message("No VIRIDIAN orders to process")})
```

```{r MICO, include = FALSE, echo = FALSE}
tryCatch({
#Join Mico store addresses
mico<-left_join(mico,micostores, by = c("ShipToAddress" = "LOCATION"))

# Add new blank columns
mico['Cust No']=""
mico['Addr4']=""
mico['Phone']=""
mico['Freight Value']=""
mico['Stkpt']=""

#Rearrange the table
impmico<-mico[c(16,4,10,27,26,22,23,28,24,25,29,9,30,31,12,11)]

# Change the column headings to match XLSX import format
colnames(impmico)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')

#Hard code and clean
impmico['Cust No']<-c(replicate(nrow(mico),"CRA001"))
impmico['Stkpt']<-c(replicate(nrow(mico),"CPS"))
impmico['Freight Value']<-as.numeric(0)

tablebuilder(impmico)
},
error = function(e){message("No MICO orders to process")})
```

```{r Combineprint}
#Join all the individual tables together and give the data a final clean (including freight calculation from Propella)
importcombined<-read.csv(pathnamer)%>%as_tibble()%>%filter(Cust.No!="")
importcombined['Prod No']<-apply(importcombined[15],2, function (x) toupper(x))
importcombined<-left_join(importcombined,generalfreight, by = c("Prod No" = "Product Code"))
importcombined<-mutate(importcombined, 'Freight Total' =  importcombined$QTY * importcombined$`Freight`)%>%.[c(1:12,19,14:16)]
importcombined[6:9]<-apply(importcombined[6:9],2, function (x) gsub("\\d{4}","",x))
importcombined[6:9]<-apply(importcombined[6:9],2, function (x) gsub("NEW ZEALAND","",x))
colnames(importcombined)<-c('CustOrd','Ref','OrdDate','Cust No','Addr1','Addr2','Addr3','Addr4','City','Pcode','Phone','Email','Freight Value','Stkpt','Prod No','QTY')
importcombined%>%write_xlsx(.,paste("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import\\Import Files\\","General order import",today(),".xlsx"))

```

```{r Archive raw files}
# Move the raw order files to an archive folder
archivetoday<-(paste0("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import\\Archive\\",today()))
archivelist<-list.files("\\\\10.103.128.1\\PropellaEDI\\live\\Orders to import", full.names = TRUE)%>%.[!file.info(.)$isdir]
dir.create(archivetoday)
file.move(archivelist,archivetoday, overwrite = FALSE)
file.remove(pathnamer)
rm(list = ls())
```

```{r warnings2}
options(warn = 1)
```


